<?php
    $navlinks = [
        [
            "text"=>"characters",
            "url"=>"/characters",
            "active"=>false
        ],
        [
            "text"=>"comics",
            "url"=>"/comics",
            "active"=>true
        ],
        [
            "text"=>"movies",
            "url"=>"/movies",
            "active"=>false
        ],
        [
            "text"=>"tv",
            "url"=>"/tv",
            "active"=>false
        ],
        [
            "text"=>"games",
            "url"=>"/games",
            "active"=>false
        ],
        [
            "text"=>"collectibles",
            "url"=>"/collectibles",
            "active"=>false
        ],
        [
            "text"=>"video",
            "url"=>"/video",
            "active"=>false
        ],
        [
            "text"=>"fans",
            "url"=>"/fans",
            "active"=>false
        ],
        [
            "text"=>"news",
            "url"=>"/news",
            "active"=>false
        ],
        [
            "text"=>"shop",
            "url"=>"/shop",
            "active"=>false
        ],

    ];

    return $navlinks;
?>